# Generated by Django 5.1.1 on 2024-10-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedorder',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
