# Generated by Django 5.1.1 on 2024-10-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_completedorder_address_payment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedorder',
            name='referral_profits',
            field=models.JSONField(default=dict),
        ),
    ]
