# Generated by Django 5.0.3 on 2025-02-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_created_at_feedback_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_fee',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
    ]
